spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/darach?useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
  data:
    redis:
      host: localhost
      password: 123456
      database: 1
      port: 6379

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

logging:
  level:
    io.sql: debug
    cn.zhxu.bs: debug
#    root: debug


xxl-job:
  address: http://localhost:8081/
  jobId: 5


minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: animate

############## Sa-Token ?? (??: https://sa-token.cc) ##############
sa-token:
  # token ??????? cookie ???
  token-name: Authorization
  # token ????????? ??30??-1 ??????
  timeout: 2592000
  # token ??????????????? token ???????????????????-1 ??????????
  active-timeout: 120000
  # ?????????????? ?? true ???????, ? false ??????????
  is-concurrent: true
  # ????????????????? token ?? true ????????? token, ? false ????????? token?
  is-share: true
  # token ?????????uuid?simple-uuid?random-32?random-64?random-128?tik?
  token-style: simple-uuid
  # ????????
  is-log: true
  jwt-secret-key: dfshk32186y9dfsabjklc.gafvdio7123/


cors-config:
    enabled: true
    allow-credentials: true
    allowed-headers: "*"
    allowed-methods: "*"
    allowed-origins: "*"
    exposed-headers: "*"
    path-pattern: "/**"
    max-age: 3600

password-encrypt:
  enabled: true
  algorithm: md5
  salt: darach

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.github.franzli347.darach.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

capture-img:
  enable: false
  # ????????????LineCaptcha, ShearCaptcha, CircleCaptcha
  type: LineCaptcha
  width: 100
  height: 100

rsa:
  public-key-path: rsa/public_key.pem
  private-key-path: rsa/private_key.pem

server:
  port: 12334

version: 1.0beta
