spring:
  profiles:
    active: user,video
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/darach?useSSL=false
    username: root
    password: 123456
    servlet:
      multipart:
        max-file-size: 100MB
  data:
    redis:
      host: localhost
      password: 123456
      database: 1
      port: 6379

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

logging:
  level:
    io.sql: debug
    cn.zhxu.bs: debug

cors-config:
  enabled: true
  allow-credentials: true
  allowed-headers: "*"
  allowed-methods: "*"
  allowed-origins: "*"
  exposed-headers: "*"
  path-pattern: "/**"
  max-age: 3600

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.github.franzli347.darach.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

rsa:
  public-key-path: rsa/public_key.pem
  private-key-path: rsa/private_key.pem