spring:
  profiles:
    active: user,video

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://20.48.77.3:3306/darach?useSSL=false
    username: root
    password: fzlfzlmysql..
    hikari:
      keepalive-time: 60000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      maximum-pool-size: 8

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: 20.78.117.200
      password: fzlfzlredis..
      database: 1
      port: 6379
      repositories:
        enabled: false

logging:
  level:
    io.sql: debug
    cn.zhxu.bs: debug

cors-config:
  enabled: true
  allow-credentials: true
  allowed-headers: "*"
  allowed-methods: "*"
  allowed-origins: "*"
  exposed-headers: "*"
  path-pattern: "/**"
  max-age: 3600

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.github.franzli347.controller

knife4j:
  enable: true
  setting:
    language: zh_cn

rsa:
  public-key-path: rsa/public_key.pem
  private-key-path: rsa/private_key.pem

