password-encrypt:
  enabled: true
  algorithm: md5
  salt: darach


sa-token:
  token-name: Authorization
  timeout: 2592000
  active-timeout: 120000
  is-concurrent: true
  is-share: true
  token-style: simple-uuid
  is-log: true
  jwt-secret-key: dfshk32186y9dfsabjklc.gafvdio7123/

capture-img:
  enable: false
  type: LineCaptcha
  width: 100
  height: 100