xxl-job:
  address: http://localhost:8081/
  jobId: 2

minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  coverBucketName: video-cover
  VideoBucketName: video

