name: native-image-compile

on: [push]

jobs:
  native-image-compile-on-host:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache SDKMAN installation
      uses: actions/cache@v3
      with:
        path: ~/.sdkman
        key: ${{ runner.os }}-sdkman-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-sdkman-
    - name: Install GraalVM with SDKMAN
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install java 21.2.0.r11-grl
        java -version
    - name: Install GraalVM Native Image
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        gu install native-image
        native-image --version
    - name: Install Maven, that uses GraalVM for later builds
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install maven
        mvn --version
    - name: Run GraalVM Native Image compilation of Spring Boot App (Maven version instead of ./compile.sh)
      run: |
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        mvn -B clean package -P native -Dmaven.test.skip=true --no-transfer-progress
