name: Build Native Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up GraalVM
      uses: DeLaGuardo/setup-graalvm@4.0
      with:
        graalvm-version: '21.1.0.java17'

    - name: Install Native Image
      run: gu install native-image

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package -DskipTests -Pnative

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: native-image
        path: target/*.jar
